import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/Provider/ThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class"
            defaultTheme="light"
            enableSystem={false}
            storageKey="dashboard-theme"
            >
          <Navbar />
       <div className="flex">
          <div className="hidden md:block h-[100vh]">
            <Sidebar />
          </div>
          <div className="p-10 w-full md:max-w-[1140px]">
           {children}
          </div>
          <Toaster />
       </div>
       </ThemeProvider>
      </body>
    </html>
  );
}
